dist: trusty
sudo: required
language:
  - c
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      # - gcc-6
      # - g++-6
      - cmake
      - gcc-multilib
      - g++-multilib

before_install:
# needed for compiling 32bit software on 64bit machine
  - sudo apt-get install gcc-multilib g++-multilib

script:
  # Link gcc-6 and g++-6 to their standard commands
  # - sudo ln -s /usr/bin/gcc-6 /usr/local/bin/gcc
  # - sudo ln -s /usr/bin/g++-6 /usr/local/bin/g++
  # # Export CC and CXX to tell cmake which compiler to use
  # - export CC=/usr/bin/gcc-6
  # - export CXX=/usr/bin/g++-6
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/lib32/:/usr/lib/gcc/x86_64-linux-gnu/7/x32/
  - ls /usr/lib32/
  # Check versions of gcc, g++ and cmake
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - git submodule init
  - git submodule update
  - cp cfe/cmake/Makefile.sample Makefile
  - cp -r cfe/cmake/sample_defs sample_defs
  - make prep
  - make
  - make install
  - ls build/exe/cpu1/
